config/routes.rb
Tvshow::Application.routes.draw do
  devise_for :users

  resources :tv_groups
  resources :tv_stations
  resources :tv_programs
  resources :users
  resources :discusses
  resources :program_groups     
  resources :discuss_relationships, :only => [:new, :create, :destroy]
  resources :user_relationships,    :only => [:create, :destroy]
  resources :user_programships,     :only => [:create, :destroy]
  resources :user_checkinships,     :only => [:create, :destroy]
  resources :discuss_commentships,  :only => [:create, :destroy]
  resources :token_authentications, :only => [:create, :destroy]
  resources :shake,                 :only => [:index]
  resources :crawler_info,          :only => [:index, :show]
  resources :crawl_program_content, :only => [:new, :create]

  devise_for :users, :controllers => { :sessions => "sessions" }
  devise_scope :user do
    resources :sessions, :only => [:create, :destroy]
  end

  root :to => 'tv_groups#index'

end

app/controllers/discusses_controller.rb
class DiscussesController < ApplicationController
  #before_filter :authenticate_user!, :except => [:index, :show]

  #show discusses index page
  def index
    @discusses = Discuss.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @discusses.to_xml }
      format.json { render :json => @discusses.to_json }
    end
  end

  #new discuss, it will be deprecated
  def new
    @discuss = Discuss.new
  end
  
  #new discuss using POST method
  def create
dsdsd
    @discuss = Discuss.new(params[:discuss])
    @discuss.time = Time.now
    @discuss.save
    
    redirect_to :action => :index
  end

  #show discuss info
  def show
    @discuss = Discuss.find(params[:id])
    @user = User.find(@discuss.user_id)
    if @discuss.discuss_type == 1
      @src_discuss = Discuss.find(@discuss.src_id)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @discuss.to_xml }
      format.json { render :json => @discuss.to_json }
    end
  end

  #edit discuss, it will be deprecated
  def edit
    @discuss = Discuss.find(params[:id])
  end

  #update discuss using PUT method
  def update
    @discuss = Discuss.find(params[:id])
    @discuss.update_attributes(params[:discuss])
  
    redirect_to :action => :show, :id => @discuss
  end

  #delete discuss using DELETE method
  def destroy
    @discuss = Discuss.find(params[:id])
    @discuss.destroy
    
    redirect_to :action => :index
  end

end

app/helpers/discusses_helper.rb
module DiscussesHelper
end

app/views/discusses/index.html.erb
<ul>
<% @discusses.each do |discuss| %>
  <li>
    <%= link_to discuss.topic, discuss_path(discuss) %>
    <%= link_to 'edit', edit_discuss_path(discuss) %>
    <%= button_to 'delete', discuss_path(discuss), :method => :delete %>
  </li>
<% end %>
</ul>
<%= link_to 'new discuss', new_discuss_path %>

app/views/discusses/show.html.erb
<% if  @discuss.program.program_type == 0 %>
  <%= "tv_program : " %>
  <%= link_to @discuss.program.name, tv_program_path(@discuss.program) %>
<% elsif @discuss.program.program_type == 1 %>
  <%= "program_group : " %>
  <%= link_to @discuss.program.name, program_group_path(@discuss.program) %>
<% end %>
<br/>

<% if (@discuss.discuss_type == 1) %>
  <%= link_to "RE: " + @src_discuss.topic, discuss_path(@src_discuss) %>
  <br/>
<% end %>

<%= "topic : " + @discuss.topic %>
<br/>
<%= "time : " + @discuss.time.to_s %>
<br/>
<%= link_to @user.name, user_path(@user) %>
<br/>
<%= "like" + @discuss.like.to_s %>
<br/>
<%= "unlike" + @discuss.dislike.to_s %>
<br/>
<%= simple_format(@discuss.content) %>
<br/>
<% if current_user != nil %>
<% comment = current_user.get_comment(@discuss)[0] %>
  <% if comment != nil  %>
    <% if comment.comment_type == -1 %>
      <%= form_tag(discuss_commentships_path, :method => 'update') do %>
        <%= hidden_field_tag 'user', current_user.id %>
        <%= hidden_field_tag 'discuss', @discuss.id %>
        <%= hidden_field_tag 'discuss_comment', comment.id %>
        <%= hidden_field_tag 'comment_type', '1' %>
        <%= submit_tag('like') %>
      <% end %>
    <% else %>
      <%= form_tag(discuss_commentships_path, :method => 'update') do %>
        <%= hidden_field_tag 'user', current_user.id %>
        <%= hidden_field_tag 'discuss', @discuss.id %>
        <%= hidden_field_tag 'discuss_comment', comment.id %>
        <%= hidden_field_tag 'comment_type', '-1' %>
        <%= submit_tag('unlike') %>
      <% end %>
    <% end %>
    <%= form_tag(discuss_commentship_path, :method => 'delete') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'discuss', @discuss.id %>
      <%= hidden_field_tag 'discuss_comment', comment.id %>
      <%= hidden_field_tag 'comment_type', '0' %>
      <%= submit_tag('remove') %>
    <% end %>  
  <% else %>
    <%= form_tag(discuss_commentships_path, :method => 'post') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'discuss', @discuss.id %>
      <%= hidden_field_tag 'comment_type', '1' %>
      <%= submit_tag("like") %>
    <% end %>
    <%= form_tag(discuss_commentships_path, :method => 'post') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'discuss', @discuss.id %>
      <%= hidden_field_tag 'comment_type', '-1' %>
      <%= submit_tag("unlike") %>
    <% end %>
  <% end %>
<% end %>
<br/>

<% @discuss.quotes.each do |quote| %>
  <li>
    <%= link_to quote.topic, discuss_path(quote) %>
  </li>
<% end %>

<p>
  <%= link_to 'reply discuss', {:controller =>'discuss_relationships', :action => 'new', :src => @discuss, 
      :program_type => @discuss.program.program_type, :program => @discuss.program} %>
</p>