config/routes.rb
Tvshow::Application.routes.draw do
  devise_for :users

  resources :tv_groups
  resources :tv_stations
  resources :tv_programs
  resources :users
  resources :discusses
  resources :program_groups     
  resources :discuss_relationships, :only => [:new, :create, :destroy]
  resources :user_relationships,    :only => [:create, :destroy]
  resources :user_programships,     :only => [:create, :destroy]
  resources :user_checkinships,     :only => [:create, :destroy]
  resources :discuss_commentships,  :only => [:create, :destroy]
  resources :token_authentications, :only => [:create, :destroy]
  resources :shake,                 :only => [:index]
  resources :crawler_info,          :only => [:index, :show]
  resources :crawl_program_content, :only => [:new, :create]

  devise_for :users, :controllers => { :sessions => "sessions" }
  devise_scope :user do
    resources :sessions, :only => [:create, :destroy]
  end

  root :to => 'tv_groups#index'

end

app/models/tv_program.rb
class TvProgram < ActiveRecord::Base
  attr_accessible :description, :episode, :image, :key_word, :name, 
                  :watch_count, :discuss_count, :checkin_count, :discusses,
                  :group_type, :program_group_id, :program_group, :program_type

  #for relationship with tv_station
  has_many :tv_programships, :dependent => :destroy
  has_many :tv_stations, :through => :tv_programships, :uniq => true

  #for watch relationship with user
  has_many :user_programships, :dependent => :destroy, :as => :program
  has_many :users, :through => :user_programships, :source => :user, :uniq => true

  #for checkin relationship with user
  has_many :user_checkinships, :dependent => :destroy, :as => :program
  has_many :checkin_users, :through => :user_checkinships, :source => :user, :uniq => true

  #for relationship with discuss
  has_many :discusses, :as => :program

  #for relationship with program_group
  belongs_to :program_group
end

app/controllers/tv_programs_controller.rb
class TvProgramsController < ApplicationController
  #before_filter :authenticate_user!, :except => [:index, :show]

  #show index page
  def index
    @programs = TvProgram.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @programs.to_xml }
      format.json { render :json => @programs.to_json }
    end
  end

  #new tv program, it will be deprecated
  def new
    @program = TvProgram.new
  end
  
  #new tv program using POST method
  def create
    @program = TvProgram.new(params[:program])
    @program.save
    
    redirect_to :action => :index
  end

  def edit
    @program = TvProgram.find(params[:program])
    @program.transaction do 
      @program.update_attributes(:name => params[:name])
      @program.update_attributes(:description => params[:description])
    end
    
    redirect_to :action => :index
  end

  #show tv program info
  def show
    if (params[:cmd] != nil) && (params[:cmd] == "detail")
      show_detail(params)
    elsif ((params[:cmd] != nil) && (params[:cmd] == "discuss") && (params[:from] != nil) && (params[:to] != nil))
      show_discusses(params)
    else
      show_simple(params)
    end
  end

  #show simple tv info
  def show_simple(params)
    @program = TvProgram.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @program.to_xml }
      format.json { render :json => @program.to_json }
    end
  end

  #show detail tv info
  def show_detail(params)
    @program = TvProgram.find(params[:id])
    program_format = format_detail_json(@program, @program.discusses)

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => program_format.to_xml }
      format.json { render :json => program_format.to_json}
    end
  end

  #show detail tv info
  def show_discusses(params)
    @program = TvProgram.find(params[:id])
    discusses_format = format_discusses_json(@program.discusses[params[:from].to_i .. params[:to].to_i])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => discusses_format.to_xml }
      format.json { render :json => discusses_format.to_json}
    end
  end

  #edit tv group, it will be deprecated
  def edit
    @program = TvProgram.find(params[:id])
  end

  #update tv group using PUT method
  def update
    @program = TvProgram.find(params[:id])
    @program.update_attributes(params[:program])
  
    redirect_to :action => :show, :id => @program
  end

  #delete tv group using DELETE method
  def destroy
    @program = TvProgram.find(params[:id])
    @program.destroy
    
    redirect_to :action => :index
  end

  #format json output function
  def format_detail_json(program, discusses)   
    program[:latest_discusses] = []
    discusses.sort!{|x, y| y.time <=> x.time}
    discusses.each do |discuss|
      discuss[:user_name] = discuss.user.name
      discuss[:user_img] = discuss.user.image
      program[:latest_discusses] << discuss      
    end    

    return program
  end

  #format json output function
  def format_discusses_json(discusses)    
    discusses_format = []
    discusses.sort!{|x, y| y.time <=> x.time}
    discusses.each do |discuss|
      discuss[:user_name] = discuss.user.name
      discuss[:user_img] = discuss.user.image
      discuss_format = discuss.to_json
      discusses_format << discuss_format
    end
    return discusses_format
  end

end

app/helpers/tv_programs_helper.rb
module TvProgramsHelper
end

app/views/tv_programs/index.html.erb
<ul>
</ul>
<%= link_to 'new tv program', new_tv_program_path %>

app/views/tv_programs/show.html.erb
<% if @program.episode == nil %>
  <%= @program.name %>
<% else %>
  <%= @program.name + "(" +  @program.episode.to_s + ")" %>
<% end %>
<% if @program.image and not @program.image.empty? %>
  <br/>
  <img src="data:image/jpg;base64,<%=@program.image %>">
<% end %>
<%= simple_format(@program.description) %> 
<br>
<%= "Key word : " + @program.key_word.to_s %> 

<br>
<% if @program.group_type != nil %>
    <%= link_to "program group : " + @program.program_group.name, program_group_path(@program.program_group) %>
<% end %>

<% if current_user != nil %>
  <% if current_user.has_watch_tv_program(@program) %>
    <%= form_tag(user_programship_path, :method => 'delete') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'tv_program', @program.id %>
      <%= submit_tag("unwatch") %>
    <% end %>
  <% else %>
    <%= form_tag(user_programships_path, :method => 'post') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'tv_program', @program.id %>
      <%= submit_tag("watch") %>
    <% end %>
  <% end %>
<% end %>
<br/>

<% if current_user != nil %>
  <% if current_user.has_checkin_tv_program(@program) %>
    <%= form_tag(user_checkinship_path, :method => 'delete') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'tv_program', @program.id %>
      <%= submit_tag("uncheckin") %>
    <% end %>
  <% else %>
    <%= form_tag(user_checkinships_path, :method => 'post') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'tv_program', @program.id %>
      <%= submit_tag("checkin") %>
    <% end %>
  <% end %>
  <br>
  <%= form_tag(new_crawl_program_content_path, :method => 'get') do %>
    <%= hidden_field_tag 'user', current_user.id %>
    <%= hidden_field_tag 'program', @program.id %>
    <%= submit_tag("crawl_program") %>
  <% end %>
<% end %>
<br/>

<br>
<%= "讨论条数:" + @program.discusses.size.to_s %>
<% @program.discusses.sort!{|x, y| y.time <=> x.time} %>
<% @program.discusses.each do |discuss| %>
  <li>
    <%= link_to discuss.content, discuss_path(discuss) %>
    <%= " by " %>
    <%= link_to discuss.user.name, user_path(discuss.user) %>
  </li>
<% end %>
<p>
  <%= link_to 'new discuss', {:controller => 'discuss_relationships', :program_type => 0, :action => 'new', :program => @program.id} %>
</p>

<br>
<%= "watch:" + @program.watch_count.to_s %>
<% @program.users.each do |user| %>
  <li>
    <%= link_to user.name, user_path(user) %>
  </li>
<% end %>

<br>
<%= "checkin:" + @program.checkin_count.to_s %>
<% @program.checkin_users.each do |user| %>
  <li>
    <%= link_to user.name, user_path(user) %>
  </li>
<% end %>