config/routes.rb
Tvshow::Application.routes.draw do
  devise_for :users

  resources :tv_groups
  resources :tv_stations
  resources :tv_programs
  resources :users
  resources :discusses
  resources :program_groups     
  resources :discuss_relationships, :only => [:new, :create, :destroy]
  resources :user_relationships,    :only => [:create, :destroy]
  resources :user_programships,     :only => [:create, :destroy]
  resources :user_checkinships,     :only => [:create, :destroy]
  resources :discuss_commentships,  :only => [:create, :destroy]
  resources :token_authentications, :only => [:create, :destroy]
  resources :shake,                 :only => [:index]
  resources :crawler_info,          :only => [:index, :show]
  resources :crawl_program_content, :only => [:new, :create]

  devise_for :users, :controllers => { :sessions => "sessions" }
  devise_scope :user do
    resources :sessions, :only => [:create, :destroy]
  end

  root :to => 'tv_groups#index'

end

app/models/program_group.rb
class ProgramGroup < ActiveRecord::Base
  attr_accessible :description, :image, :interval, :key_word, :name, :total_episode, :discusses,
                  :group_type, :tv_programs, :watch_count, :discuss_count, :checkin_count, :program_type

  has_many :tv_programs

  #for watch relationship with user
  has_many :user_programships, :dependent => :destroy, :as => :program
  has_many :watch_users, :through => :user_programships, :source => :user, :uniq => true

  #for checkin relationship with user
  has_many :user_checkinships, :dependent => :destroy, :as => :program
  has_many :checkin_users, :through => :user_checkinships, :source => :user, :uniq => true

  #for relationship with discuss
  has_many :discusses, :as => :program

end

app/controllers/program_groups_controller.rb
class ProgramGroupsController < ApplicationController

  #show program group index page
  def index
    @program_groups = ProgramGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @program_groups.to_xml }
      format.json { render :json => @program_groups.to_json }
    end
  end

  #show program group info
  def show

    @program_group = ProgramGroup.find(params[:id])
    @program_group[:tv_programs] = @program_group.tv_programs

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @program_group.to_xml }
      format.json { render :json => @program_group.to_json }
    end
  end

end

app/helpers/program_groups_helper.rb
module ProgramGroupsHelper
end

app/views/program_groups/index.html.erb
<ul>
<%= "Total program group Number = " + @program_groups.size.to_s %>
<br>
<% @program_groups.each do |group| %>
  <li>
    <%= link_to group.name, program_group_path(group) %>
    <%= " (" + group.tv_programs.size().to_s + ")" %>
  </li>
<% end %>
</ul>

app/views/program_groups/show.html.erb
<% if @program_group.total_episode == nil %>
  <%= @program_group.name %>
<% else %>
  <%= @program_group.name + "(" +  @program_group.total_episode.to_s + ")" %>
<% end %>
<% if @program_group.image and not @program_group.image.empty? %>
  <br/>
  <img src="data:image/jpg;base64,<%=@program_group.image %>">
<% end %>
<%= simple_format(@program_group.description) %> 
<br>
<%= "Key word : " + @program_group.key_word.to_s %> 

<br>
<%= "related tv program:" + @program_group.tv_programs.size.to_s %>
<% @program_group.tv_programs.each do |tv_program| %>
  <li>
    <%= link_to tv_program.name + tv_program.tv_programships[0].begin_time.to_s, tv_program_path(tv_program) %>
  </li>
<% end %>

<% if current_user != nil %>
  <% if current_user.has_watch_program_group(@program_group) %>
    <%= form_tag(user_programship_path, :method => 'delete') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'program_group', @program_group.id %>
      <%= submit_tag("unwatch") %>
    <% end %>
  <% else %>
    <%= form_tag(user_programships_path, :method => 'post') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'program_group', @program_group.id %>
      <%= submit_tag("watch") %>
    <% end %>
  <% end %>
<% end %>
<br/>

<% if current_user != nil %>
  <% if current_user.has_checkin_program_group(@program_group) %>
    <%= form_tag(user_checkinship_path, :method => 'delete') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'program_group', @program_group.id %>
      <%= submit_tag("uncheckin") %>
    <% end %>
  <% else %>
    <%= form_tag(user_checkinships_path, :method => 'post') do %>
      <%= hidden_field_tag 'user', current_user.id %>
      <%= hidden_field_tag 'program_group', @program_group.id %>
      <%= submit_tag("checkin") %>
    <% end %>
  <% end %>
  <br>
  <%= form_tag(new_crawl_program_content_path, :method => 'get') do %>
    <%= hidden_field_tag 'user', current_user.id %>
    <%= hidden_field_tag 'program', @program_group.id %>
    <%= hidden_field_tag 'program_type', @program_group.program_type %>
    <%= submit_tag("crawl_program") %>
  <% end %>
<% end %>
<br/>

<% if current_user != nil and @program_group.type == 0 %>
  <%= form_tag(edit_program_group, :method => 'get') do %>
    <%= hidden_field_tag 'user', current_user.id %>
    <%= hidden_field_tag 'program', @program_group.id %>
    <%= hidden_field_tag 'program_type', @program_group.program_type %>
    <%= submit_tag("edit_interval_program") %>
  <% end %>
<% end %>
<br/>

<br>
<%= "讨论条数:" + @program_group.discusses.size.to_s %>
<% @program_group.discusses.sort!{|x, y| y.time <=> x.time} %>
<% @program_group.discusses.each do |discuss| %>
  <li>
    <%= link_to discuss.content, discuss_path(discuss) %>
    <%= " by " %>
    <%= link_to discuss.user.name, user_path(discuss.user) %>
  </li>
<% end %>
<p>
  <%= link_to 'new discuss', {:controller => 'discuss_relationships', :program_type => 1, :action => 'new', :program => @program_group.id} %>
</p>

<br>
<%= "watch:" + @program_group.watch_count.to_s %>
<% @program_group.watch_users.each do |user| %>
  <li>
    <%= link_to user.name, user_path(user) %>
  </li>
<% end %>


<br>
<%= "checkin:" + @program_group.checkin_count.to_s %>
<% @program_group.checkin_users.each do |user| %>
  <li>
    <%= link_to user.name, user_path(user) %>
  </li>
<% end %>