config/routes.rb
Tvshow::Application.routes.draw do
  devise_for :users

  resources :tv_groups
  resources :tv_stations
  resources :tv_programs
  resources :users
  resources :discusses
  resources :program_groups     
  resources :discuss_relationships, :only => [:new, :create, :destroy]
  resources :user_relationships,    :only => [:create, :destroy]
  resources :user_programships,     :only => [:create, :destroy]
  resources :user_checkinships,     :only => [:create, :destroy]
  resources :discuss_commentships,  :only => [:create, :destroy]
  resources :token_authentications, :only => [:create, :destroy]
  resources :shake,                 :only => [:index]
  resources :crawler_info,          :only => [:index, :show]
  resources :crawl_program_content, :only => [:new, :create]

  devise_for :users, :controllers => { :sessions => "sessions" }
  devise_scope :user do
    resources :sessions, :only => [:create, :destroy]
  end

  root :to => 'tv_groups#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :token_authenticatable

  before_save :ensure_authentication_token

  # accessible (or protected) attributes
  attr_accessible :email, :password, :password_confirmation, :remember_me, :authentication_token
  attr_accessible :name, :address, :age, :id_card, :image,  :qq, :telephone, :version, :weibo,  :discusses, 
                  :checkin_count, :discuss_count, :watch_count, :followee_count, :follower_count, :msg_count

  #for relationship with user  
  has_many :follower_relationships, :class_name => "UserRelationship"
  has_many :followers, :through => :follower_relationships, :source => :follower, :uniq => true

  has_many :followee_relationships, :class_name => "UserRelationship", :foreign_key => "follower_id"
  has_many :followees, :through => :followee_relationships, :source => :user, :uniq => true  

  #for checkin relationship with tv_program
  has_many :user_checkinships, :dependent => :destroy
  has_many :checkin_tv_programs, :through => :user_checkinships, :source => :program, 
           :source_type => 'TvProgram', :uniq => true

  #for checkin relationship with program_group
  has_many :user_checkinships, :dependent => :destroy
  has_many :checkin_program_groups, :through => :user_checkinships, :source => :program, 
           :source_type => 'ProgramGroup', :uniq => true

  #for watch relationship with tv_program
  has_many :user_programships, :dependent => :destroy
  has_many :tv_programs, :through => :user_programships, :source => :program,
           :source_type => 'TvProgram', :uniq => true

  #for watch relationship with program_group
  has_many :user_programships, :dependent => :destroy
  has_many :program_groups, :through => :user_programships, :source => :program,
           :source_type => 'ProgramGroup', :uniq => true

  #for relationship with discuss
  has_many :discusses

  #for relationship with discuss comments
  has_many :discuss_comments

  def get_followees   
    return self.followees      
  end

  def get_followers
    return self.followers
  end

  def has_followee(user)
    return self.followees.include?(user)
  end

  def has_follower(user)
    return self.followers.include?(user)
  end 

  def has_watch_tv_program(program)
    return self.tv_programs.include?(program)
  end

  def has_watch_program_group(program)
    return self.program_groups.include?(program) 
  end

  def get_watch_programs
    return self.tv_programs + self.program_groups
  end

  def has_checkin_tv_program(program)
    return self.checkin_tv_programs.include?(program)
  end

  def has_checkin_program_group(program)
    return self.checkin_program_groups.include?(program) 
  end

  def get_checkin_programs
    return self.checkin_tv_programs + self.checkin_program_groups
  end

  def get_discusses
    return self.discusses
  end

  def get_comment(discuss)
    return self.discuss_comments.where(:discuss_id => discuss.id)
  end

  def get_comments
    return self.discuss_comments
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authenticate_user!, :except => [:index, :show]

  #show user index page
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @users.to_xml }
      format.json { render :json => @users.to_json }
    end
  end

  #new user, it will be deprecated
  def new
    @user = User.new
  end
  
  #new tv station using POST method
  def create
    @user = User.new(params[:user])
    @user.save
    
    redirect_to :action => :index
  end

  #show user info
  def show
    if (params[:cmd] != nil) && (params[:cmd] == "detail")
      show_detail(params)
    elsif ((params[:cmd] != nil) && (params[:cmd] == "followers"))
      show_followers(params)
    elsif ((params[:cmd] != nil) && (params[:cmd] == "followees"))
      show_followees(params)
    elsif ((params[:cmd] != nil) && (params[:cmd] == "discusses"))
      show_discusses(params)
    elsif ((params[:cmd] != nil) && (params[:cmd] == "watch_programs"))
      show_watch_programs(params)
    elsif ((params[:cmd] != nil) && (params[:cmd] == "checkin_programs"))
      show_checkin_programs(params)
    elsif ((params[:cmd] != nil) && (params[:cmd] == "followers_detail"))
      show_followers_detail(params)
    elsif ((params[:cmd] != nil) && (params[:cmd] == "followees_detail"))
      show_followees_detail(params)
    else
      show_simple(params)
    end
  end

  #show simple user info
  def show_simple(params)
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user.to_xml }
      format.json { render :json => @user.to_json }
    end
  end

  #show user followers
  def show_followers(params)
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user.get_followers.to_xml }
      format.json { render :json => @user.get_followers.to_json }
    end
  end

  #show user followees
  def show_followees(params)
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user.get_followees.to_xml }
      format.json { render :json => @user.get_followees.to_json }
    end
  end

  #show user followers detail
  def show_followers_detail(params)
    @user = User.find(params[:id])

    followers_detail = []
    @user.get_followers.each do |follower|     
      follower[:latest_checkin] = follower.get_checkin_programs.sort_by{ |p| p.updated_at }.last
      followers_detail << follower
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => followers_detail.to_xml }
      format.json { render :json => followers_detail.to_json }
    end
  end

  #show user followees detail
  def show_followees_detail(params)
    @user = User.find(params[:id])

    followees_detail = []
    @user.get_followees.each do |followee|
      followee[:latest_checkin] = followee.get_checkin_programs.sort_by{ |p| p.updated_at }.last
      followees_detail << followee
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => followees_detail.to_xml }
      format.json { render :json => followees_detail.to_json }
    end
  end

  #show user discusses
  def show_discusses(params)
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user.get_discusses.to_xml }
      format.json { render :json => @user.get_discusses.to_json }
    end
  end

  #show user watch programs
  def show_watch_programs(params)
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user.get_watch_programs.to_xml }
      format.json { render :json => @user.get_watch_programs.to_json }
    end
  end

  #show user watch programs
  def show_checkin_programs(params)
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user.get_checkin_programs.to_xml }
      format.json { render :json => @user.get_checkin_programs.to_json }
    end
  end

  #show user detail information
  def show_detail(params)
    @user = User.find(params[:id])
    @user[:followers] = @user.get_followers
    @user[:followees] = @user.get_followees
    @user[:discusses] = @user.get_discusses
    @user[:watch_programs] = @user.get_watch_programs
    @user[:checkin_programs] = @user.get_checkin_programs

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user.to_xml }
      format.json { render :json => @user.to_json }
    end
  end

  #edit user, it will be deprecated
  def edit
    @user = User.find(params[:id])
  end

  #update user using PUT method
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
  
    redirect_to :action => :show, :id => @user
  end

  #delete tv group using DELETE method
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    redirect_to :action => :index
  end
 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<ul>
<% @users.each do |user| %>
  <li>
    <%= link_to user.name, user_path(user) %>
    <%= link_to 'edit', edit_user_path(user) %>
    <%= button_to 'delete', user_path(user), :method => :delete %>
  </li>
<% end %>
</ul>
<%= link_to 'new user', new_user_path %>

app/views/users/show.html.erb
<%= @user.name %>
<br>
<%= "email : " + @user.email %>
<%= simple_format(@user.address) %>
<% if @user == current_user %>
<% elsif @user.has_follower(current_user) %>
  <%= form_tag(user_relationship_path, :method => 'delete') do %>
    <%= hidden_field_tag 'user', @user.id %>
    <%= hidden_field_tag 'follower', current_user.id %>
    <%= submit_tag("unfollow") %>
  <% end %>
<% elsif current_user != nil %>
  <%= form_tag(user_relationships_path, :method => 'post') do %>
    <%= hidden_field_tag 'user', @user.id %>
      <%= hidden_field_tag 'follower', current_user.id %>
    <%= submit_tag("follow") %>
  <% end %>
<% end %>
<br/>

<%= "watch tv_program" + @user.tv_programs.size.to_s + ") : " %>
<% @user.tv_programs.each do |program| %>
  <li>
    <%= link_to program.name, tv_program_path(program) %>
  </li>
<% end %>
<br/>

<%= "watch program group(" + @user.program_groups.size.to_s + ") : " %>
<% @user.program_groups.each do |program| %>
  <li>
    <%= link_to program.name, program_group_path(program) %>
  </li>
<% end %>
<br/>

<%= "checkin tv program(" + @user.checkin_tv_programs.size.to_s + ") : " %>
<% @user.checkin_tv_programs.each do |program| %>
  <li>
    <%= link_to program.name, tv_program_path(program) %>
  </li>
<% end %>
<br/>

<%= "checkin program group(" + @user.checkin_program_groups.size.to_s + ") : " %>
<% @user.checkin_program_groups.each do |program| %>
  <li>
    <%= link_to program.name, program_group_path(program) %>
  </li>
<% end %>
<br/>

<%= "followee(" + @user.followee_count.to_s + ") : " %>
<% @user.get_followees().each do |followee| %>
  <li>
    <%= link_to followee.name, user_path(followee) %>
  </li>
<% end %>
<br/>

<%= "follower(" + @user.follower_count.to_s + ")" %>
<% @user.get_followers().each do |follower| %>
  <li>
    <%= link_to follower.name, user_path(follower) %>
  </li>
<% end %>
<br/>

<%= "discuss(" + @user.discuss_count.to_s + ")" %>
<% @user.discusses.each do |discuss| %>
  <li>
    <%= link_to discuss.content, discuss_path(discuss) %>
  </li>
<% end %>
<br/>

<%= "message(" + @user.msg_count.to_s + ")" %>
<br/>

<%= "version(" + @user.version.to_s + ")" %>

<% if user_signed_in? and @user == current_user %>
  <li>
  <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% end %>